name: bytes
description: A package that unifies Uint8List and ByteData.
version: 0.8.0
author: Jim Philbin <jfphilbin@gmail.com>

homepage: https://github.com/OpenDICOMweb/bytes

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  constants:
    path: C:/odw/constants
    version: ^0.8.0

dev_dependencies:
  benchmark_harness: any
  coverage: any
  grinder: ^0.8.0
  test:  any
  test_tools:
    path: C:/odw/test_tools
    version: ^0.8.0
  rng:
    path: C:/odw/rng
    version: ^0.8.0
