name: bytes
description: A package that unifies Uint8List and ByteData.
version: 0.7.6
author: Jim Philbin <jfphilbin@gmail.com>

homepage: https://github.com/OpenDICOMweb/bytes

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  base:
    path: C:/odw/base
    version: ^0.7.6

dev_dependencies:
  benchmark_harness: any
  coverage: any
  grinder: ^0.8.0
  test:  any
  test_tools:
    path: C:/odw/test_tools
    version: ^0.7.5
  rng:
    path: C:/odw/sdk/rng
    version: ^0.8.0
